/var/spool/slurmd/job130090/slurm_script: line 8: ​: command not found
+ date
Tue Dec 21 17:04:46 EST 2021
+ python hvss_extract_isolated.py

Bad key "mathtext.fallback" on line 346 in
/hildafs/home/tcabrera/.config/matplotlib/stylelib/bhdynamics.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.2.2/matplotlibrc.template
or from the matplotlib source distribution

Bad key "xtick.labelcolor" on line 487 in
/hildafs/home/tcabrera/.config/matplotlib/stylelib/bhdynamics.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.2.2/matplotlibrc.template
or from the matplotlib source distribution
N=10000
	Loading data...
	Generating pro data...
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	convert_type_f: strange input type_f (< 0?)
	Generating singles data...

real	0m17.749s
user	0m15.656s
sys	0m0.468s
